const Ziggy = {
    url: 'http:\/\/localhost:8000',
    port: 8000,
    defaults: {},
    routes: {
        'sanctum.csrf-cookie': { uri: 'sanctum\/csrf-cookie', methods: ['GET', 'HEAD'] },
        home: { uri: '\/', methods: ['GET', 'HEAD'] },
        dashboard: { uri: 'dashboard', methods: ['GET', 'HEAD'] },
        'notifications.dismiss': {
            uri: 'notifications\/{notification}\/dismiss',
            methods: ['POST'],
            parameters: ['notification'],
            bindings: { notification: 'id' },
        },
        'student.dashboard': { uri: 'student\/dashboard', methods: ['GET', 'HEAD'] },
        'student.account': { uri: 'student\/account', methods: ['GET', 'HEAD'] },
        'payment.create': { uri: 'student\/payment', methods: ['GET', 'HEAD'] },
        'reminders.read': { uri: 'student\/reminders\/{reminder}\/read', methods: ['POST'], parameters: ['reminder'], bindings: { reminder: 'id' } },
        'reminders.dismiss': {
            uri: 'student\/reminders\/{reminder}\/dismiss',
            methods: ['POST'],
            parameters: ['reminder'],
            bindings: { reminder: 'id' },
        },
        'students.index': { uri: 'students', methods: ['GET', 'HEAD'] },
        'students.create': { uri: 'students\/create', methods: ['GET', 'HEAD'] },
        'students.store': { uri: 'students', methods: ['POST'] },
        'students.show': { uri: 'students\/{student}', methods: ['GET', 'HEAD'], parameters: ['student'] },
        'students.edit': { uri: 'students\/{student}\/edit', methods: ['GET', 'HEAD'], parameters: ['student'], bindings: { student: 'id' } },
        'students.update': { uri: 'students\/{student}', methods: ['PUT', 'PATCH'], parameters: ['student'], bindings: { student: 'id' } },
        'students.destroy': { uri: 'students\/{student}', methods: ['DELETE'], parameters: ['student'], bindings: { student: 'id' } },
        'students.payments.store': { uri: 'students\/{student}\/payments', methods: ['POST'], parameters: ['student'], bindings: { student: 'id' } },
        'students.advance-workflow': {
            uri: 'students\/{student}\/advance-workflow',
            methods: ['POST'],
            parameters: ['student'],
            bindings: { student: 'id' },
        },
        'students.workflow-history': {
            uri: 'students\/{student}\/workflow-history',
            methods: ['GET', 'HEAD'],
            parameters: ['student'],
            bindings: { student: 'id' },
        },
        'students.archive': { uri: 'students-archive', methods: ['GET', 'HEAD'] },
        'student-fees.index': { uri: 'student-fees', methods: ['GET', 'HEAD'] },
        'student-fees.create-student': { uri: 'student-fees\/create-student', methods: ['GET', 'HEAD'] },
        'student-fees.store-student': { uri: 'student-fees\/store-student', methods: ['POST'] },
        'student-fees.create': { uri: 'student-fees\/create', methods: ['GET', 'HEAD'] },
        'student-fees.store': { uri: 'student-fees', methods: ['POST'] },
        'student-fees.show': { uri: 'student-fees\/{userId}', methods: ['GET', 'HEAD'], parameters: ['userId'] },
        'student-fees.edit': { uri: 'student-fees\/{userId}\/edit', methods: ['GET', 'HEAD'], parameters: ['userId'] },
        'student-fees.update': { uri: 'student-fees\/{userId}', methods: ['PUT'], parameters: ['userId'] },
        'student-fees.payments.store': { uri: 'student-fees\/{userId}\/payments', methods: ['POST'], parameters: ['userId'] },
        'student-fees.export-pdf': { uri: 'student-fees\/{userId}\/export-pdf', methods: ['GET', 'HEAD'], parameters: ['userId'] },
        'transactions.index': { uri: 'transactions', methods: ['GET', 'HEAD'] },
        'transactions.download': { uri: 'transactions\/download', methods: ['GET', 'HEAD'] },
        'transactions.receipt': {
            uri: 'transactions\/{transaction}\/receipt',
            methods: ['GET', 'HEAD'],
            parameters: ['transaction'],
            bindings: { transaction: 'id' },
        },
        'account.pay-now': { uri: 'account\/pay-now', methods: ['POST'] },
        'transactions.create': { uri: 'transactions\/create', methods: ['GET', 'HEAD'] },
        'transactions.store': { uri: 'transactions', methods: ['POST'] },
        'transactions.show': {
            uri: 'transactions\/{transaction}',
            methods: ['GET', 'HEAD'],
            parameters: ['transaction'],
            bindings: { transaction: 'id' },
        },
        'transactions.destroy': {
            uri: 'transactions\/{transaction}',
            methods: ['DELETE'],
            parameters: ['transaction'],
            bindings: { transaction: 'id' },
        },
        'admin.dashboard': { uri: 'admin\/dashboard', methods: ['GET', 'HEAD'] },
        'users.index': { uri: 'admin\/users', methods: ['GET', 'HEAD'] },
        'users.create': { uri: 'admin\/users\/create', methods: ['GET', 'HEAD'] },
        'users.store': { uri: 'admin\/users', methods: ['POST'] },
        'users.show': { uri: 'admin\/users\/{user}', methods: ['GET', 'HEAD'], parameters: ['user'], bindings: { user: 'id' } },
        'users.edit': { uri: 'admin\/users\/{user}\/edit', methods: ['GET', 'HEAD'], parameters: ['user'], bindings: { user: 'id' } },
        'users.update': { uri: 'admin\/users\/{user}', methods: ['PUT', 'PATCH'], parameters: ['user'], bindings: { user: 'id' } },
        'users.destroy': { uri: 'admin\/users\/{user}', methods: ['DELETE'], parameters: ['user'], bindings: { user: 'id' } },
        'admin.users.deactivate': { uri: 'admin\/users\/{user}\/deactivate', methods: ['POST'], parameters: ['user'], bindings: { user: 'id' } },
        'admin.users.reactivate': { uri: 'admin\/users\/{user}\/reactivate', methods: ['POST'], parameters: ['user'], bindings: { user: 'id' } },
        'notifications.index': { uri: 'admin\/notifications', methods: ['GET', 'HEAD'] },
        'notifications.create': { uri: 'admin\/notifications\/create', methods: ['GET', 'HEAD'] },
        'notifications.store': { uri: 'admin\/notifications', methods: ['POST'] },
        'notifications.show': {
            uri: 'admin\/notifications\/{notification}',
            methods: ['GET', 'HEAD'],
            parameters: ['notification'],
            bindings: { notification: 'id' },
        },
        'notifications.edit': {
            uri: 'admin\/notifications\/{notification}\/edit',
            methods: ['GET', 'HEAD'],
            parameters: ['notification'],
            bindings: { notification: 'id' },
        },
        'notifications.update': {
            uri: 'admin\/notifications\/{notification}',
            methods: ['PUT', 'PATCH'],
            parameters: ['notification'],
            bindings: { notification: 'id' },
        },
        'notifications.destroy': {
            uri: 'admin\/notifications\/{notification}',
            methods: ['DELETE'],
            parameters: ['notification'],
            bindings: { notification: 'id' },
        },
        'admin.payment-terms.index': { uri: 'admin\/payment-terms', methods: ['GET', 'HEAD'] },
        'admin.payment-terms.update-due-date': {
            uri: 'admin\/payment-terms\/{paymentTerm}\/due-date',
            methods: ['POST'],
            parameters: ['paymentTerm'],
            bindings: { paymentTerm: 'id' },
        },
        'admin.payment-terms.bulk-due-date': { uri: 'admin\/payment-terms\/bulk-due-date', methods: ['POST'] },
        'accounting.dashboard': { uri: 'accounting\/dashboard', methods: ['GET', 'HEAD'] },
        'accounting.transactions.index': { uri: 'accounting\/transactions', methods: ['GET', 'HEAD'] },
        'accounting-workflows.index': { uri: 'accounting-workflows', methods: ['GET', 'HEAD'] },
        'accounting-workflows.create': { uri: 'accounting-workflows\/create', methods: ['GET', 'HEAD'] },
        'accounting-workflows.store': { uri: 'accounting-workflows', methods: ['POST'] },
        'accounting-workflows.show': {
            uri: 'accounting-workflows\/{transaction}',
            methods: ['GET', 'HEAD'],
            parameters: ['transaction'],
            bindings: { transaction: 'id' },
        },
        'accounting-workflows.update': {
            uri: 'accounting-workflows\/{transaction}',
            methods: ['PUT'],
            parameters: ['transaction'],
            bindings: { transaction: 'id' },
        },
        'accounting-workflows.destroy': {
            uri: 'accounting-workflows\/{transaction}',
            methods: ['DELETE'],
            parameters: ['transaction'],
            bindings: { transaction: 'id' },
        },
        'accounting-workflows.submit': {
            uri: 'accounting-workflows\/{transaction}\/submit',
            methods: ['POST'],
            parameters: ['transaction'],
            bindings: { transaction: 'id' },
        },
        'workflows.index': { uri: 'workflows', methods: ['GET', 'HEAD'] },
        'workflows.create': { uri: 'workflows\/create', methods: ['GET', 'HEAD'] },
        'workflows.store': { uri: 'workflows', methods: ['POST'] },
        'workflows.show': { uri: 'workflows\/{workflow}', methods: ['GET', 'HEAD'], parameters: ['workflow'], bindings: { workflow: 'id' } },
        'workflows.edit': { uri: 'workflows\/{workflow}\/edit', methods: ['GET', 'HEAD'], parameters: ['workflow'] },
        'workflows.update': { uri: 'workflows\/{workflow}', methods: ['PUT', 'PATCH'], parameters: ['workflow'], bindings: { workflow: 'id' } },
        'workflows.destroy': { uri: 'workflows\/{workflow}', methods: ['DELETE'], parameters: ['workflow'], bindings: { workflow: 'id' } },
        'approvals.index': { uri: 'approvals', methods: ['GET', 'HEAD'] },
        'approvals.show': { uri: 'approvals\/{approval}', methods: ['GET', 'HEAD'], parameters: ['approval'], bindings: { approval: 'id' } },
        'approvals.approve': { uri: 'approvals\/{approval}\/approve', methods: ['POST'], parameters: ['approval'], bindings: { approval: 'id' } },
        'approvals.reject': { uri: 'approvals\/{approval}\/reject', methods: ['POST'], parameters: ['approval'], bindings: { approval: 'id' } },
        'profile.destroy': { uri: 'settings\/profile', methods: ['DELETE'] },
        'profile.edit': { uri: 'settings\/profile', methods: ['GET', 'HEAD'] },
        'profile.update': { uri: 'settings\/profile', methods: ['PATCH'] },
        'profile.update-picture': { uri: 'settings\/profile-picture', methods: ['POST'] },
        'profile.remove-picture': { uri: 'settings\/profile-picture', methods: ['DELETE'] },
        'password.edit': { uri: 'settings\/password', methods: ['GET', 'HEAD'] },
        'password.update': { uri: 'settings\/password', methods: ['PUT'] },
        appearance: { uri: 'settings\/appearance', methods: ['GET', 'HEAD'] },
        'settings.profile.picture': { uri: 'settings\/profile\/picture', methods: ['POST'] },
        register: { uri: 'register', methods: ['GET', 'HEAD'] },
        'register.store': { uri: 'register', methods: ['POST'] },
        login: { uri: 'login', methods: ['GET', 'HEAD'] },
        'login.store': { uri: 'login', methods: ['POST'] },
        'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'] },
        'password.email': { uri: 'forgot-password', methods: ['POST'] },
        'password.reset': { uri: 'reset-password\/{token}', methods: ['GET', 'HEAD'], parameters: ['token'] },
        'password.store': { uri: 'reset-password', methods: ['POST'] },
        'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'] },
        'verification.verify': { uri: 'verify-email\/{id}\/{hash}', methods: ['GET', 'HEAD'], parameters: ['id', 'hash'] },
        'verification.send': { uri: 'email\/verification-notification', methods: ['POST'] },
        'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'] },
        'password.confirm.store': { uri: 'confirm-password', methods: ['POST'] },
        logout: { uri: 'logout', methods: ['POST'] },
        'storage.local': { uri: 'storage\/{path}', methods: ['GET', 'HEAD'], wheres: { path: '.*' }, parameters: ['path'] },
        'storage.local.upload': { uri: 'storage\/{path}', methods: ['PUT'], wheres: { path: '.*' }, parameters: ['path'] },
    },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
