<?php

namespace App\Providers;

use App\Models\StudentPaymentTerm;
use App\Observers\StudentPaymentTermObserver;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * NOTE: Do NOT share Inertia data here.
     * All shared props are managed exclusively by HandleInertiaRequests middleware
     * to prevent overwrite conflicts and ensure full user objects are passed.
     */
    public function boot(): void
    {
        // ── Payment-term sum integrity observer ───────────────────────────────
        //
        // Enforces: SUM(student_payment_terms.amount) per assessment
        //           == student_assessments.total_assessment
        //
        // This observer is the application-layer counterpart to the MySQL trigger
        // created in migration 2026_03_17_000002_add_payment_term_sum_trigger.
        // It runs in ALL environments (including SQLite tests) and throws a
        // readable ValidationException instead of a raw DB signal error.
        StudentPaymentTerm::observe(StudentPaymentTermObserver::class);

        // ── Laravel Telescope (local + staging only) ──────────────────────────
        //
        // Telescope records every DB query, job, event, log, and HTTP request.
        // It makes the following problems immediately visible in the dev UI:
        //
        //   • Double-recalculate loop (Bug #4 effect): you'll see two identical
        //     AccountService::recalculate() DB queries fire per payment save.
        //
        //   • N+1 queries: Telescope highlights repeated queries on the same
        //     table within a single request.
        //
        //   • Slow queries: anything > 100ms is flagged in the Queries panel.
        //
        // INSTALLATION (run once per environment):
        //   composer require laravel/telescope --dev
        //   php artisan telescope:install
        //   php artisan migrate
        //
        // Telescope is gated to local/staging via TelescopeServiceProvider
        // (generated by telescope:install). It must NEVER run in production
        // as it stores all request payloads including sensitive data.
        //
        // If Telescope is not yet installed, this block is a no-op.

        // ── Laravel Pulse (staging + production-safe option) ─────────────────
        //
        // Pulse provides lightweight performance dashboards (slow queries,
        // job throughput, exception counts) with a much smaller storage footprint
        // than Telescope. It is safe to enable in production.
        //
        // INSTALLATION (run once):
        //   composer require laravel/pulse
        //   php artisan vendor:publish --provider="Laravel\Pulse\PulseServiceProvider"
        //   php artisan migrate
        //
        // Then visit /pulse (protected by the 'admin' gate in PulseServiceProvider).
        //
        // Recommended split:
        //   Local dev   → Telescope (full request inspection)
        //   Staging     → Both (Telescope for debugging + Pulse for perf baseline)
        //   Production  → Pulse only
    }
}